/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Navigation-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-notification_filled': '&#xe9de;',
		'icon-user_filled': '&#xe9df;',
		'icon-received_email': '&#xe9dc;',
		'icon-sent_email': '&#xe9dd;',
		'icon-chatbot': '&#xe9d6;',
		'icon-close_left': '&#xe9d7;',
		'icon-lync': '&#xe9d8;',
		'icon-move': '&#xe9d9;',
		'icon-open_right': '&#xe9da;',
		'icon-pin': '&#xe9db;',
		'icon-accommodation': '&#xe9ce;',
		'icon-bus': '&#xe9cf;',
		'icon-cab_2': '&#xe9d0;',
		'icon-flight': '&#xe9d1;',
		'icon-rupee': '&#xe9d2;',
		'icon-skype': '&#xe9d3;',
		'icon-timeline': '&#xe9d4;',
		'icon-train': '&#xe9d5;',
		'icon-fav_filled': '&#xe9cd;',
		'icon-pause': '&#xe9cb;',
		'icon-tree_view': '&#xe9cc;',
		'icon-emp_balance': '&#xe9be;',
		'icon-onsite_compensation': '&#xe9ca;',
		'icon-disability': '&#xe9c4;',
		'icon-educationcap': '&#xe9c5;',
		'icon-psp': '&#xe9c6;',
		'icon-selectedrole': '&#xe9c7;',
		'icon-sublocation': '&#xe9c8;',
		'icon-yoga': '&#xe9c9;',
		'icon-ascendingorder': '&#xe9b5;',
		'icon-callrequest': '&#xe9b6;',
		'icon-descendingorder': '&#xe9b7;',
		'icon-guestpass': '&#xe9b8;',
		'icon-idcard': '&#xe9b9;',
		'icon-list': '&#xe9ba;',
		'icon-payslip': '&#xe9bb;',
		'icon-pricetag': '&#xe9bc;',
		'icon-seat': '&#xe9bd;',
		'icon-skillname': '&#xe9bf;',
		'icon-SMS': '&#xe9c0;',
		'icon-trendnxt': '&#xe9c1;',
		'icon-vehiclepass': '&#xe9c2;',
		'icon-videoconf': '&#xe9c3;',
		'icon-facilities': '&#xe9b4;',
		'icon-moveall_left': '&#xe9b2;',
		'icon-moveall_right': '&#xe9b3;',
		'icon-leave': '&#xe9af;',
		'icon-voice_mute': '&#xe9b0;',
		'icon-voice': '&#xe9b1;',
		'icon-jpg': '&#xe9a7;',
		'icon-pdf': '&#xe9a8;',
		'icon-png': '&#xe9a9;',
		'icon-PPT': '&#xe9aa;',
		'icon-psd': '&#xe9ab;',
		'icon-share': '&#xe9ac;',
		'icon-word': '&#xe9ad;',
		'icon-xl': '&#xe9ae;',
		'icon-Code': '&#xe9a4;',
		'icon-handshake': '&#xe9a5;',
		'icon-trophy': '&#xe9a6;',
		'icon-bar_chart': '&#xe9a3;',
		'icon-cubicle_location': '&#xe9a2;',
		'icon-rating_feedback': '&#xe99f;',
		'icon-run_lines': '&#xe9a0;',
		'icon-spoc': '&#xe9a1;',
		'icon-announce_advertise': '&#xe999;',
		'icon-facebook': '&#xe99a;',
		'icon-googleplus': '&#xe99b;',
		'icon-linkedin': '&#xe99c;',
		'icon-twitter': '&#xe99d;',
		'icon-youtube': '&#xe99e;',
		'icon-insurance': '&#xe998;',
		'icon-award_badge': '&#xe98c;',
		'icon-cab_car': '&#xe98d;',
		'icon-home': '&#xe98e;',
		'icon-hotel_building': '&#xe98f;',
		'icon-insurance_group': '&#xe990;',
		'icon-location_distance': '&#xe991;',
		'icon-savings': '&#xe992;',
		'icon-school_fees': '&#xe993;',
		'icon-superannuation_pension': '&#xe994;',
		'icon-training_2': '&#xe995;',
		'icon-training': '&#xe996;',
		'icon-wbp': '&#xe997;',
		'icon-img_helpline': '&#xe989;',
		'icon-wipro_live': '&#xe98a;',
		'icon-yammer': '&#xe98b;',
		'icon-accessibility': '&#xe900;',
		'icon-add_note': '&#xe901;',
		'icon-add': '&#xe902;',
		'icon-admin': '&#xe903;',
		'icon-analysis': '&#xe904;',
		'icon-announcement': '&#xe905;',
		'icon-appstore': '&#xe906;',
		'icon-archive': '&#xe907;',
		'icon-arrow_down': '&#xe908;',
		'icon-arrow_drop_down': '&#xe909;',
		'icon-arrow_drop_left': '&#xe90a;',
		'icon-arrow_drop_right': '&#xe90b;',
		'icon-arrow_drop_up': '&#xe90c;',
		'icon-arrow_left': '&#xe90d;',
		'icon-arrow_right': '&#xe90e;',
		'icon-arrow_up': '&#xe90f;',
		'icon-assessment': '&#xe910;',
		'icon-assets_declared': '&#xe911;',
		'icon-assets_undeclared': '&#xe912;',
		'icon-assets': '&#xe913;',
		'icon-attachment': '&#xe914;',
		'icon-back_arrow': '&#xe915;',
		'icon-block': '&#xe916;',
		'icon-browse': '&#xe917;',
		'icon-burger_menu': '&#xe918;',
		'icon-business': '&#xe919;',
		'icon-calendar': '&#xe91a;',
		'icon-call_end': '&#xe91b;',
		'icon-call': '&#xe91c;',
		'icon-camera': '&#xe91d;',
		'icon-cart': '&#xe91e;',
		'icon-check_mark': '&#xe91f;',
		'icon-circle_add': '&#xe920;',
		'icon-circle_alert': '&#xe921;',
		'icon-circle_arrowdown': '&#xe922;',
		'icon-circle_arrowleft': '&#xe923;',
		'icon-circle_arrowright': '&#xe924;',
		'icon-circle_arrowup': '&#xe925;',
		'icon-circle_remove': '&#xe926;',
		'icon-close_circle': '&#xe927;',
		'icon-close': '&#xe928;',
		'icon-color': '&#xe929;',
		'icon-computer': '&#xe92a;',
		'icon-copy': '&#xe92b;',
		'icon-create_folder': '&#xe92c;',
		'icon-create': '&#xe92d;',
		'icon-cut': '&#xe92e;',
		'icon-delete': '&#xe92f;',
		'icon-devices': '&#xe930;',
		'icon-discussion': '&#xe931;',
		'icon-dislike': '&#xe932;',
		'icon-doc_download': '&#xe933;',
		'icon-doc_publish': '&#xe934;',
		'icon-doc_upload': '&#xe935;',
		'icon-document': '&#xe936;',
		'icon-drafts': '&#xe937;',
		'icon-dummy_profile': '&#xe938;',
		'icon-edit': '&#xe939;',
		'icon-email': '&#xe93a;',
		'icon-event_available': '&#xe93b;',
		'icon-event_cancel': '&#xe93c;',
		'icon-event_note': '&#xe93d;',
		'icon-expand': '&#xe93e;',
		'icon-faq': '&#xe93f;',
		'icon-fav_line': '&#xe940;',
		'icon-feedback': '&#xe941;',
		'icon-file_document': '&#xe942;',
		'icon-file_download': '&#xe943;',
		'icon-file_upload': '&#xe944;',
		'icon-filter': '&#xe945;',
		'icon-find_app': '&#xe946;',
		'icon-float_bottom': '&#xe947;',
		'icon-float_left': '&#xe948;',
		'icon-float_right': '&#xe949;',
		'icon-float_top': '&#xe94a;',
		'icon-folder': '&#xe94b;',
		'icon-font': '&#xe94c;',
		'icon-goals_objectives': '&#xe94d;',
		'icon-headset_mic': '&#xe94e;',
		'icon-headset': '&#xe94f;',
		'icon-help': '&#xe950;',
		'icon-history': '&#xe951;',
		'icon-ideas': '&#xe952;',
		'icon-image': '&#xe953;',
		'icon-info': '&#xe954;',
		'icon-keyboard': '&#xe955;',
		'icon-like': '&#xe956;',
		'icon-link': '&#xe957;',
		'icon-location': '&#xe958;',
		'icon-logout': '&#xe959;',
		'icon-mac_monitor': '&#xe95a;',
		'icon-map': '&#xe95b;',
		'icon-memory': '&#xe95c;',
		'icon-mobile': '&#xe95d;',
		'icon-more_h': '&#xe95e;',
		'icon-more_v': '&#xe95f;',
		'icon-multylingual': '&#xe960;',
		'icon-navigator': '&#xe961;',
		'icon-news': '&#xe962;',
		'icon-notification': '&#xe963;',
		'icon-open_folder': '&#xe964;',
		'icon-other_setting': '&#xe965;',
		'icon-pass_ticket': '&#xe966;',
		'icon-password': '&#xe967;',
		'icon-paste': '&#xe968;',
		'icon-pie_chart': '&#xe969;',
		'icon-print': '&#xe96a;',
		'icon-rating': '&#xe96b;',
		'icon-receipt': '&#xe96c;',
		'icon-recycle': '&#xe96d;',
		'icon-refresh': '&#xe96e;',
		'icon-remove': '&#xe96f;',
		'icon-reset': '&#xe970;',
		'icon-save': '&#xe971;',
		'icon-search_content': '&#xe972;',
		'icon-search': '&#xe973;',
		'icon-send': '&#xe974;',
		'icon-settings': '&#xe975;',
		'icon-shared_folder': '&#xe976;',
		'icon-shrink': '&#xe977;',
		'icon-status_complete': '&#xe978;',
		'icon-status_inprogress': '&#xe979;',
		'icon-status_pending': '&#xe97a;',
		'icon-store': '&#xe97b;',
		'icon-teleservices': '&#xe97c;',
		'icon-time': '&#xe97d;',
		'icon-transact': '&#xe97e;',
		'icon-ui': '&#xe97f;',
		'icon-unlock': '&#xe980;',
		'icon-user_id': '&#xe981;',
		'icon-video_play': '&#xe982;',
		'icon-view': '&#xe983;',
		'icon-virtual': '&#xe984;',
		'icon-warning': '&#xe985;',
		'icon-wifi': '&#xe986;',
		'icon-zhoomin': '&#xe987;',
		'icon-zhoomout': '&#xe988;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
